# podman build -t casa-env:0.1 .
FROM almalinux:8

RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled powertools && \
    dnf install -y epel-release && \
    yum update -y

# Casacore deps
RUN yum -y install cmake cmake-gui wget git gcc-gfortran gcc-c++ flex    bison \
        blas blas-devel  lapack lapack-devel cfitsio cfitsio-devel \
        ncurses ncurses-devel readline readline-devel \
        fftw fftw-devel hdf5 hdf5-devel libgomp wcslib wcslib-devel

# Python deps
RUN yum -y install python38-devel boost boost-devel \
        python38-numpy boost-python3 python38-pip swig \
        libjpeg-turbo-devel libxslt-devel

RUN pip3 install --user matplotlib packaging certifi scipy traitlets

# Other deps
RUN yum -y install xerces-c-devel libgomp openmpi-devel environment-modules libxml2-devel \
 java-11-openjdk rsync libtool libsqlite3x-devel \
 ccache xerces-c gsl-devel && \
 bash && \
                              \
 yum install --skip-broken --forcearch x86_64 -y https://casa.nrao.edu/download/repo/el7/x86_64/rpfits-2.23-02.el7.x86_64.rpm && \
                                  \
 yum install -y https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/s/shtool-2.0.8-11.el7.noarch.rpm

RUN echo "source /usr/share/Modules/init/bash" >> ~/.bashrc && \
    echo "module load mpi/openmpi-aarch64" >> ~/.bashrc && \
    source ~/.bashrc

